name: Deploy Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Autenticar com GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configurar gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy para Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: agente-dashboard
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/agente-dashboard
          region: us-central1